### ISSUE TITLE
grid should be related to axis

### ISSUE THREAD

**Issue by jordansread** [USGS-R/gsplot#100]
we don't want the users to need to work too hard to get grid lines at the same ticks as axis ticks.

**Comment by ldecicco-USGS** [comment]
Need an example of when this doesn't work as expected.

**Comment by mhines-usgs** [comment]
This is out of uvhydro

primary series plot

``` r
uvhplot <- lines(uvhplot, NA, NA, log='y') %>%
      axis(side=c(1),at=seq(uv_lims$xlim[1], uv_lims$xlim[2], by="days"),labels=as.character(1:length(dates))) %>%
      axis(side=2) %>%
      grid(nx=length(dates)-1, ny=NULL, equilogs=FALSE) %>%
      legend(location="below", title="") %>%
      title(main="", xlab=date_lbl, ylab=primary_lbl) 
```

![image](https://cloud.githubusercontent.com/assets/6920344/9277926/dc2a321c-4272-11e5-8fca-59875bfe9cb7.png)

secondary series plot

``` r
 sec_uvhplot <- legend(sec_uvhplot, location="below", title="") %>%
      axis(side=c(1),at=seq(secondary_lims$xlim[1], secondary_lims$xlim[2], by="days"),labels=as.character(1:length(sec_dates))) %>%
      title(main="", xlab=sec_date_lbl, ylab=secondary_lbl) %>%
      axis(side=2) %>%
      axis(side=4) %>%
      grid(nx=length(sec_dates)+1, ny=NULL, equilogs=FALSE)
```

![image](https://cloud.githubusercontent.com/assets/6920344/9277896/aec1ac74-4272-11e5-8122-014ce4882531.png)

Expected behavior is that the grid lines would go from the ticks. From my extensive googling it seems like I could use abline instead of grid to get them where I want.

**Comment by mhines-usgs** [comment]
Although would be nice if it behaved well when nx=NULL and ny=NULL [like this stack-o post](http://stackoverflow.com/questions/8081931/r-grid-line-consistent-with-ticks-on-axis)
