### ISSUE TITLE
segments vs lines?

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/gsplot#119]
I know recently I heard @jread-usgs talk about minimizing the amount of code we have, and I was wondering what the necessity of having both a segments function and lines function is? My first impression is that you can accomplish the same thing (see below), but there might be some other functionality I am missing. 

``` r
gs <- gsplot()
gsNew <- points(gs, y=1, x=2, xlim=c(0,NA),ylim=c(0,NA),
            col="blue", pch=18, legend.name="Points")
gsNew <- lines(gsNew, c(3,4,3), c(2,4,6), legend.name="Lines")
gsNew <- abline(gsNew, b=1, a=0, legend.name="1:1")
gsNew <- legend(gsNew, "topleft",title="Awesome!")
gsNew <- grid(gsNew)
gsNew <- segments(gsNew, x0=2, y0=0.75, y1=1.25)
gsNew
```

``` r
gs <- gsplot()
gsNew <- points(gs, y=1, x=2, xlim=c(0,NA),ylim=c(0,NA),
            col="blue", pch=18, legend.name="Points")
gsNew <- lines(gsNew, c(3,4,3), c(2,4,6), legend.name="Lines")
gsNew <- abline(gsNew, b=1, a=0, legend.name="1:1")
gsNew <- legend(gsNew, "topleft",title="Awesome!")
gsNew <- grid(gsNew)
gsNew <- lines(gsNew, x=c(2,2), y=c(0.75, 1.25))
gsNew
```

**Comment by jordansread** [comment]
Good question - in terms of minimizing code, I was referring to the handling functions that are internal to gsplot. i think these wrapper functions for graphics should be supported as much as possible, so that you can do (almost) anything in gsplot that you can do in base graphics, just a lot more efficiently. So I would say we keep segments and at some point we will be adding a bunch more too...luckily these functions are pretty lightweight to add.

**Comment by lindsayplatt** [comment]
Ok, sounds good -- just thought I would bring it up :smiley:

**Comment by jordansread** [comment]
Good question to bring up (and don't hesitate to bring up more).
