### ISSUE TITLE
grid + axis causes funkyness

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/gsplot#180]
Works:

``` r
gs <- gsplot() %>%
      points(y=c(3,1,2), x=1:3)  %>%
      grid()
      # axis(side=c(3,4), labels=FALSE) 
gs
```

Works:

``` r
gs <- gsplot() %>%
      points(y=c(3,1,2), x=1:3)  %>%
      # grid()
      axis(side=c(3,4), labels=FALSE) 
gs
```

Doesn't work:

``` r
gs <- gsplot() %>%
      points(y=c(3,1,2), x=1:3)  %>%
      grid() %>%
      axis(side=c(3,4), labels=FALSE) 
gs
```

**Comment by ldecicco-USGS** [comment]
Important note: when debugging...if it errors during `print`, you have to run `dev.off()` right away or `par` stuff will be all screwed up.

**Comment by lindsayplatt** [comment]
@mhines-usgs this is probably why your axis calls for 4 aren't working in uvhydrograph

**Comment by mhines-usgs** [comment]
le sigh.

**Comment by lindsayplatt** [comment]
I have finally located the issue! In calc_views --> [order_views](https://github.com/USGS-R/gsplot/blob/master/R/order_views.R), it enters the if statement in line 8 when you have grid() or bgCol() in your gsplot object. bgCol has the same issue with overwriting the axes calls. 

The code within the if statement of `order_views` renamed the "axis" sublist of `views` into "view", creating two "view" sublists. Therefore, the [plot.window](https://github.com/USGS-R/gsplot/blob/master/R/print.R#L51) call in `print` was trying to find an x limit from the list that contained axis details.

**Comment by lindsayplatt** [comment]
I fixed it to plot the axes, but for some reason it plots them on the outside when grid() is used and on the inside when grid is not used...investigating this now.

**Comment by ldecicco-USGS** [comment]
:+1: :+1: 

Two thumbs up!

**Comment by lindsayplatt** [comment]
The difference occurs in `do.call(getFromNamespace(name, package), params)` of the override.R function (called when `axis(axisParams)` is called in the draw_axis function). I went down that rabbit hole and honestly can't find the differences between these two calls:

``` r
## ticks on the inside
gs <- gsplot() %>%
    points(y=c(3,1,2), x=1:3)  %>%
    axis(side=c(3,4), labels=FALSE) 
gs

## ticks on the outside
gs <- gsplot() %>%
    points(y=c(3,1,2), x=1:3)  %>%
    axis(side=c(3,4), labels=FALSE) %>%
    grid()
gs
```

I think that R must have some default for outside ticks when grid lines exist because they clash (even axes 1 and 2 have outside ticks when grid is called). So if you want inside ticks with a grid, you will have to manually specify that (submitting the PR soon so that this will work): 

``` r
gs <- gsplot() %>%
      points(y=c(3,1,2), x=1:3)  %>%
      grid() %>%
      axis(side=c(3,4), labels=FALSE, tck=0.03) 
gs
```
