### ISSUE TITLE
current version drops `cex` when not set

### ISSUE THREAD

**Issue by jordansread** [USGS-R/gsplot#226]
![image](https://cloud.githubusercontent.com/assets/2349007/9645166/ae9985f6-518f-11e5-9c54-bb93cc65c3fc.png)

for 

``` R
usrDef <- gsplot(mar=c(4,4,4,4), xaxs='r', yaxs='r') %>% 
     points(x=1, y=2, side=c(3,2), legend.name="Points 1", cex=3, xlab='cat') %>% 
     points(x=3, y=4, side=c(1,4), legend.name="Points 2", pch=5, col="red", ylab=expression(paste("Discharge in ",ft^3/s))) %>% 
     lines(x=c(3,4,3), y=c(2,4,6), legend.name="Lines 1", lty=5, col="orange") %>%
     lines(x=c(1,2,5), y=c(1,8,5), legend.name="Lines 2", lwd=3, ylab='Science!', xlab='dogs') %>%  
     legend(x=1.5,y=4)
usrDef
```

in `legendParams`:

```
$pt.cex
[1]  3 NA NA NA
```

**Comment by jordansread** [comment]
so `pt.cex` gets NA instead of the default (probably 1)

**Comment by lindsayplatt** [comment]
This whole method needs to be revisited - filling in NA is also messing with density specifications (see #219)

**Comment by jordansread** [comment]
curious @lindsaycarr , why did we move from a list to a data.frame for these legend styles? What problem did that solve?

**Comment by lindsayplatt** [comment]
since I was trying to add all legend arguments at one time, and call legend at the very end, there needed to be fillers when something wasn't specified so that it would still align with its corresponding args. For instance, 

``` r
gs <- gsplot() %>%
points(1:5, col="blue", pch=21, legend.name="points 1") %>%
points(5:1, col="red", legend.name="points2") %>%
points(7:10, pch=5, legend.name="points3") %>%
legend()
gs
```

If it was a list, since points2 does not specify `pch` it needs a filler, otherwise the `pch=5` from points3 would end up applying to points2. So I chose a data frame because it automatically filled in NAs. Obviously, this is not a sound approach
