### ISSUE TITLE
Axis Date/POSIXct

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/gsplot#272]
If the user wanted to call axis.Date or axis.POSIXct...they'd have problems:

```
gs <- gsplot() %>%
      points(x=seq.Date(as.Date("2000-01-01"),as.Date("2010-01-01"),length.out = 20),
             y=1:20,axes=FALSE) %>%
      axis(1, at=seq.Date(as.Date("2000-01-01"),as.Date("2010-01-01"),length.out = 5))
gs
```

**Comment by jordansread** [comment]
in base, this would require you to do:

``` r
plot(x=seq.Date(as.Date("2000-01-01"),as.Date("2010-01-01"),length.out = 20),
             y=1:20,axes=FALSE, ylab=NA,xlab=NA)
axis.Date(1, at=seq.Date(as.Date("2000-01-01"),as.Date("2010-01-01"),length.out = 5))
box()
```

because `axis(1, at=seq.Date(as.Date("2000-01-01"),as.Date("2010-01-01"),length.out = 5))` does the same thing as gsplot's `axis`

options:
1) gsplot has an override function for `axis.Date` and `axis.POSIXct`:

``` r
gs <- gsplot() %>%
      points(x=seq.Date(as.Date("2000-01-01"),as.Date("2010-01-01"),length.out = 20),
             y=1:20,axes=FALSE) %>%
      axis.Date(1, at=seq.Date(as.Date("2000-01-01"),as.Date("2010-01-01"),length.out = 5))
gs
```

2) gsplot tries to be smart w/ `axis` based on the class of the incoming data. This is tricky because the Date and POSIX axis sneak in an `x` param:

``` r
names(formals(graphics::axis))
 [1] "side"      "at"        "labels"    "tick"      "line"      "pos"       "outer"     "font"      "lty"       "lwd"       "lwd.ticks" "col"       "col.ticks" "hadj"      "padj"      "..."      
names(formals(graphics::axis.Date))
[1] "side"   "x"      "at"     "format" "labels" "..." 
```

probably doable though. 

I think the way it works right now might not be a bug, since it mimics the way base would do it. 

But, it does bring up the issue of trying to use a function that `gsplot` doesn't have an override for:

``` r
gs <- gsplot() %>%
      points(x=seq.Date(as.Date("2000-01-01"),as.Date("2010-01-01"),length.out = 20),
             y=1:20,axes=FALSE) %>%
      axis.Date(1, at=seq.Date(as.Date("2000-01-01"),as.Date("2010-01-01"),length.out = 5))
Error in side%%2 : non-numeric argument to binary operator
```

which is not a very helpful error

**Comment by lindsayplatt** [comment]
@ldecicco-USGS @jread-usgs not sure what the original issue with this was, but with what is currently on the master branch, I get:

![image](https://cloud.githubusercontent.com/assets/13220910/20022686/b8aa291c-a2a9-11e6-9a9c-534549609da5.png)
