### ISSUE TITLE
bgCol broken: covers up data

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/gsplot#349]
``` r
gs <- gsplot() %>%
   points(1:100, rnorm(100,mean=10000, sd=1000), log="y") %>%
   bgCol('lightgrey')
gs

gs2 <- gsplot() %>%
   bgCol('lightgrey') %>% 
   points(1:100, rnorm(100,mean=10000, sd=1000), log="y")
gs2
```

both look like this:
![image](https://cloud.githubusercontent.com/assets/13220910/16095246/71051f82-3309-11e6-837e-7f1635c117a6.png)

**Comment by jordansread** [comment]
can you provide the base code that makes this look the way you think it should behave?

**Comment by lindsayplatt** [comment]
Changing to something that is not generating random numbers, so I've included the gsplot code again

``` r
#gsplot
gs <- gsplot() %>%
    bgCol('lightgrey') %>%
    points(1:4,1:4)
gs

# base
plot(1:4, 1:4)
x1 <- par("usr")[1]
x2 <- par("usr")[2]
y1 <- par("usr")[3]
y2 <- par("usr")[4]
rect(x1,y1,x2,y2,col = 'lightgrey', border = NA)
points(1:4,1:4)
```

Should look like this:
![image](https://cloud.githubusercontent.com/assets/13220910/16096326/090474dc-330e-11e6-8eee-883badfdb6af.png)

**Comment by ldecicco-USGS** [comment]
We use to re-order the gsplot object so that the `bgCol` would happen first, but that logic was removed. It certainly needs to get put back in place. 

We could put a default transparent `rect` in the object when the `gsplot` is initialized (like I was proposing with the `plot.default` default arguments). That is one way I guess to guarantee it's the first thing plotted without re-ordering the gsplot list at the end (I don't remember why that was so toxic, but it seemed to be).

**Comment by jordansread** [comment]
part of the question here is how the calls/args in `global` are rendered. Right now, `par` is the only thing that goes into `global`, but our intent was `bgCol`, `title`, and I think `legend`(?). it would be good if we had a consistent way to handle these for rendering including order.
