### ISSUE TITLE
get rid of the camelCase

### ISSUE THREAD

**Issue by jordansread** [USGS-R/gsplot#464]
use_the_underscores. 

At a minimum for all of the public functions.

**Comment by lindsayplatt** [comment]
Just did a regex search through all of our files `[a-z][A-Z]`. Here's what functions are still camel case (all internal):

- ~`get_axTicks`, `usr_axTicks`, `grid_axTicks`~ (probably OK because `axTicks` is base function)
- `appendLegendColumnInfo`
- `appendLegendPositionConfiguration`
- `append_keepTZ`

**Comment by ldecicco-USGS** [comment]
Yeah, I'd vote keep `axTick` as is, otherwise I'm pretty indifferent with a _slight_ preference to switch for consistency.

**Comment by lindsayplatt** [comment]
We've got a lot of camel case in variable names and in examples. Not worth changing in my opinion, so I am closing this. Someone can reopen if they feel otherwise.
