### ISSUE TITLE
create templates (or similar) for gsplot plotting defaults

### ISSUE THREAD

**Issue by jordansread** [USGS-R/gsplot#5]
Things like default tick lengths, colors, line weights, font sizes, font types, legend placement, etc.

yaml within the package?

See `ggplot2` themes for inspiration http://docs.ggplot2.org/current/theme.html

**Comment by ldecicco-USGS** [comment]
Look at ggplot2 themes:

Example:
https://github.com/jrnold/ggthemes/blob/master/R/economist.R#L194

We might want to (way down the road) create a function to read a ggplot2 theme, and convert it to gsplot config.

**Comment by lindsayplatt** [comment]
@ldecicco-USGS is this referring to the guidelines set by the USGS plotting guidelines you sent me earlier this week?

**Comment by jordansread** [comment]
@ldecicco-USGS is this supposed to be a yaml?

**Comment by ldecicco-USGS** [comment]
yeah, this is an old Issue, but once @jiwalker-usgs makes the yaml, let's start populating it with things that make sense....ie stuff in the plotting guidelines. If the yaml isn't ready (or won't be soon), the same parameters can be added to the `graphTemplate` in config.R:

https://github.com/USGS-R/gsplot/blob/master/R/config.R#L19

**Comment by lindsayplatt** [comment]
Ok, makes sense. Could you send the guidelines again? It was in my shared folder, but now it's not

**Comment by jiwalker-usgs** [comment]
I have the yaml working, but the way it deals with options is a problem right now.  I'll try to wrap that up and make a PR.

**Comment by jordansread** [comment]
thanks `w`

**Comment by lindsayplatt** [comment]
There are some defaults that are specified in the function call and in the default.yaml file. Do we want to be consistent with where default features are defined?

Example: callouts
- color specified in yaml file: https://github.com/USGS-R/gsplot/blob/master/inst/extdata/default.yaml#L33-L34
- length and angle specified in callouts.R: https://github.com/USGS-R/gsplot/blob/master/R/callouts.R#L29

**Comment by lindsayplatt** [comment]
**Guidelines to add to yaml:**
- legend title should always default to "EXPLANATION"
  - change line 14 in the yaml file to code below
  - this does not work right now, but changing defaults in the _legend.R_ file do

``` r
    legend:
        title: "EXPLANATION"
        location: "bottomleft"
```

**Guidelines that should be added elsewhere:**
- commas for numbers > 999, produce this:

``` r
    x <- c(1000, 2000, 3000)
    y <- c(2000, 1000, 2000)
    labs <- prettyNum(x, big.mark=",", scientific=FALSE)
    gs <- gsplot() %>% 
          points(x, y) %>%
          axis(side=1, at=x, labels=labs)
    gs
```
- font types (#39)
  - specify type, size, and style (bold, italicized)
  - Axes captions: Univers 57 Condensed, 8 or 9 pt
  - Axes labels: Univers 57 Condensed, 7 or 8 pt
  - Legend title: Univers 67 Condensed Bold, 8 or 9 pt, uppercase 
  - Title: Univers 67 Condensed, 8 or 9 pt (Bold Oblique for letters, Bold for words following letter)
  - ps=12 specifies the pointsize, but only for the overall graph in par()
  - should be able to specify different pointsizes for title or axis labels

``` r
        x <- c(1000, 2000, 3000)
        y <- c(2000, 1000, 2000)
        gs <- gsplot(ps=10) %>% 
            points(x, y, legend.name="Some Points") %>%
            legend() %>%
            title(main="GRAPH")
        gs
```
- grid graphs with the same parameters should have only one x- and y-axis label
- numeric scale for axes must be able to extend to zero (e.g. 1,3,5.. would not work because it extends to -1)
- arithmetic grids must be square (see bottom of page 18 of the plotting guide))
- single-column, double-column, and sidetitle figures (save as specific size for reports in the print.R file?)

**Comment by ldecicco-USGS** [comment]
My suggestion for the next sprint is to have someone re-create the (appropriate for `gsplot`) graphs in `smwrGraphs` using only the config.yaml file and the data. The relevant files are here:

https://github.com/USGS-R/smwrGraphs/blob/master/inst/doc/LineScatter.pdf
https://github.com/USGS-R/smwrGraphs/blob/master/inst/doc/GraphAdditions.pdf
https://github.com/USGS-R/smwrGraphs/blob/master/inst/doc/DateAxisFormats.pdf
https://github.com/USGS-R/smwrGraphs/blob/master/inst/doc/GraphGallery.pdf
maybe:
https://github.com/USGS-R/smwrGraphs/blob/master/inst/doc/ProbabilityPlots.pdf

For example, the first graph in the first link:

``` r
set.seed(2576)
X <- runif(33)
Y <- runif(33)
Z <- rep(c("A","B","C"),11)
X12 <- X[1:12]
Z12 <- LETTERS[1:12]

library(gsplot)

gsplot() %>%
  points(X, Y, col="darkblue")

```

So, just futzing with config.yaml, can we get:

![2016-06-20_15-37-23](https://cloud.githubusercontent.com/assets/1105215/16209496/f273cba8-36fc-11e6-888c-c8efd67e4658.png)

**Comment by ldecicco-USGS** [comment]
1. Write gsplot code to reproduce graph
2. Edit config.yaml to see how close the style can get.

**Comment by lindsayplatt** [comment]
@wdwatkins maybe break this out into multiple issues (for each template type)

**Comment by wdwatkins** [comment]
We need to be able to get every graph in each of the pdfs above?

**Comment by jordansread** [comment]
I think the main point is just that it not be extremely painful to create those w/ `gsplot`

**Comment by lindsayplatt** [comment]
Separated into multiple issues: #361, #362, #363, and #364
